import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <body className={inter.className}>

            <header className="w-full bg-gray-100 dark:bg-gray-800 shadow">
                <nav className="container mx-auto flex items-center justify-between py-4 px-4 md:px-6">
                    <Link className="text-lg font-bold text-gray-900 dark:text-gray-50" href="#">
                        Team 9
                    </Link>
                    <div className="flex items-center space-x-4">
                        <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="/">
                            Home
                        </Link>
                        <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="/Gallery">
                            Gallery
                        </Link>
                        <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="/About">
                            About
                        </Link>
                    </div>
                </nav>
            </header>
            {children}</body>
        </html>
    );
}
 
